# Generated by Django 4.2 on 2023-04-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.CharField(max_length=50)),
                ('emmails', models.EmailField(max_length=30)),
                ('dob', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
