# Generated by Django 4.1.8 on 2023-05-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('cuisine', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=700)),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
