# Generated by Django 4.1.8 on 2023-05-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_h_name_order_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='orderd',
        ),
    ]
