# Generated by Django 4.1.8 on 2023-05-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_order_orderd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orderd',
            new_name='ord',
        ),
    ]
