# Generated by Django 4.1.8 on 2023-05-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_ord_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ord',
            new_name='Ordn',
        ),
    ]
