# Generated by Django 4.1.8 on 2023-05-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_ord_ordn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=500)),
                ('cusine', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=700)),
            ],
        ),
    ]
